version: '3.9'

services:
  # Spring Boot Application
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - springmysql
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "ollama.endpoint": "http://ai:11434/api/generate",
        "ollama.model": "deepseek-r1:7b",
        "ollama.timeout.connect": "30000",
        "ollama.timeout.read": "60000",
        "logging.level.org.springframework": "INFO",
        "spring.main.lazy-initialization": "true"
      }'
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          memory: 256M

  # MySQL Database
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - springmysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama AI Service
  ai:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ./models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
      - OLLAMA_MODELS=/root/.ollama/models
      - MODEL_NAME=deepseek-r1:7b
    ports:
      - "11434:11434"
    networks:
      - springmysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


networks:
  springmysql:
    driver: bridge

volumes:
  db:
    driver: local